"""Generate checked-in WOFF2 subsets; normal Vite builds need no Python tools.

Run: python3 scripts/subset-fonts.py
Requires: fonttools[woff] (fontTools and brotli).
"""

import hashlib
from io import BytesIO
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "public/fonts/fusion-pixel-12px-proportional-zh_hans.ttf.woff2"
LOCALE = ROOT / "src/constants/locales/zh-hans.ts"
OUTPUT = ROOT / "public/fonts/fusion-pixel"
CSS = ROOT / "src/styles/fonts.css"


def unicode_ranges(codepoints):
    """Use exact, disjoint ranges so a glyph never downloads two subsets."""
    ranges = []
    start = previous = None
    for codepoint in sorted(codepoints):
        if previous is not None and codepoint == previous + 1:
            previous = codepoint
            continue
        if start is not None:
            ranges.append((start, previous))
        start = previous = codepoint
    if start is not None:
        ranges.append((start, previous))
    return ", ".join(
        f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}"
        for start, end in ranges
    )


def make_subset(name, codepoints, source_ttf):
    # Reconstruct WOFF2 outlines once, not once for every Unicode block.
    font = TTFont(BytesIO(source_ttf), recalcTimestamp=False)
    options = subset.Options()
    options.flavor = "woff2"
    options.recalc_timestamp = False
    # Preserve copyright and license records along with the family metadata.
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    font.flavor = "woff2"
    temporary = OUTPUT / f"{name}.woff2"
    font.save(temporary)
    font.close()
    with TTFont(temporary) as saved:
        assert set(saved.getBestCmap()) == codepoints, f"Missing glyphs in {name}"
    data = temporary.read_bytes()
    filename = f"{name}-{hashlib.sha256(data).hexdigest()[:12]}.woff2"
    temporary.replace(OUTPUT / filename)
    return {
        "file": filename,
        "bytes": len(data),
        "glyphs": len(codepoints),
        "unicodeRange": unicode_ranges(codepoints),
    }


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    CSS.parent.mkdir(parents=True, exist_ok=True)
    manifest_path = OUTPUT / "manifest.json"
    old_files = []
    if manifest_path.exists():
        old_files = [entry["file"] for entry in json.loads(manifest_path.read_text())["subsets"]]
    with TTFont(SOURCE, recalcTimestamp=False) as font:
        supported = set(font.getBestCmap())
        font.flavor = None
        buffer = BytesIO()
        font.save(buffer)
        source_ttf = buffer.getvalue()

    latin = {
        cp for cp in supported
        if cp < 0x0250 or 0x0300 <= cp <= 0x036F or 0x2000 <= cp <= 0x206F
    }
    # Site copy shares one small subset. User names, articles and other
    # languages load only their relevant remaining Unicode block(s).
    ui = ({ord(char) for char in LOCALE.read_text(encoding="utf-8")} & supported) - latin
    groups = [("latin", latin), ("ui", ui)]
    remaining = supported - latin - ui
    # Pack sparse ranges too, keeping CSS and the number of deployed files small.
    ordered = sorted(remaining)
    for offset in range(0, len(ordered), 256):
        points = set(ordered[offset:offset + 256])
        groups.append((f"unicode-{offset // 256:03d}", points))

    covered = set()
    entries = []
    for name, points in groups:
        assert not covered & points, f"Overlapping font subset: {name}"
        covered.update(points)
        entries.append(make_subset(name, points, source_ttf))
    assert covered == supported, "Font subsetting dropped supported characters"

    rules = ["/* Generated by scripts/subset-fonts.py. Do not edit by hand. */"]
    for entry in entries:
        rules.append(
            "@font-face {\n"
            "  font-family: 'Fusion-Pixel-Zh-Hans';\n"
            f"  src: url('/fonts/fusion-pixel/{entry['file']}') format('woff2');\n"
            "  font-display: swap;\n"
            "  font-style: normal;\n"
            "  font-weight: 400;\n"
            f"  unicode-range: {entry['unicodeRange']};\n"
            "}"
        )
    CSS.write_text("\n\n".join(rules) + "\n", encoding="utf-8")
    manifest = {
        "source": SOURCE.name,
        "sourceSha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        "sourceBytes": SOURCE.stat().st_size,
        "glyphs": len(supported),
        "subsets": entries,
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    current_files = {entry["file"] for entry in entries}
    for filename in set(old_files) - current_files:
        if Path(filename).name == filename and filename.endswith(".woff2"):
            (OUTPUT / filename).unlink(missing_ok=True)
    for entry in entries[:2]:
        print(f"{entry['file']}: {entry['glyphs']} glyphs, {entry['bytes']:,} bytes")
    print(f"Preserved {len(supported):,} characters in {len(entries)} subsets.")


if __name__ == "__main__":
    main()
